/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "test_utilities/text_assertions.h"
#include "assembler/assemble.h"
#include "parser/parse.h"
#include "processor/process.h"
#include "processor/instruction.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_TryAssembleProgram_should_outputInstructionBytes_when_lineIsValidAssemblyInstruction(void);
extern void test_TryAssembleProgram_should_outputDataBytes_when_lineIsValidAssemblyData(void);
extern void test_TryAssembleProgram_should_outputInstructionWithReference_when_instructionReferencesInstruction(void);
extern void test_TryAssembleProgram_should_outputInstructionWithReference_when_instructionReferencesData(void);
extern void test_TryAssembleProgram_should_outputErrorNoMatchingOverload_when_instructionHasIncorrectNumberOfParams(void);
extern void test_TryAssembleProgram_should_outputErrorNoMatchingOverload_when_instructionHasImmediateValueInsteadOfRegister(void);
extern void test_TryAssembleProgram_should_outputErrorNoMatchingOverload_when_instructionHasUndefinedMnemonic(void);
extern void test_TryAssembleProgram_should_outputErrorUndefinedLabel_when_instructionReferencesUndefinedLabel(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======Parameterized Test Wrappers=====*/

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("./assembler/tests/assemble_tests.c");
  run_test(test_TryAssembleProgram_should_outputInstructionBytes_when_lineIsValidAssemblyInstruction, "test_TryAssembleProgram_should_outputInstructionBytes_when_lineIsValidAssemblyInstruction", 37);
  run_test(test_TryAssembleProgram_should_outputDataBytes_when_lineIsValidAssemblyData, "test_TryAssembleProgram_should_outputDataBytes_when_lineIsValidAssemblyData", 56);
  run_test(test_TryAssembleProgram_should_outputInstructionWithReference_when_instructionReferencesInstruction, "test_TryAssembleProgram_should_outputInstructionWithReference_when_instructionReferencesInstruction", 71);
  run_test(test_TryAssembleProgram_should_outputInstructionWithReference_when_instructionReferencesData, "test_TryAssembleProgram_should_outputInstructionWithReference_when_instructionReferencesData", 95);
  run_test(test_TryAssembleProgram_should_outputErrorNoMatchingOverload_when_instructionHasIncorrectNumberOfParams, "test_TryAssembleProgram_should_outputErrorNoMatchingOverload_when_instructionHasIncorrectNumberOfParams", 119);
  run_test(test_TryAssembleProgram_should_outputErrorNoMatchingOverload_when_instructionHasImmediateValueInsteadOfRegister, "test_TryAssembleProgram_should_outputErrorNoMatchingOverload_when_instructionHasImmediateValueInsteadOfRegister", 134);
  run_test(test_TryAssembleProgram_should_outputErrorNoMatchingOverload_when_instructionHasUndefinedMnemonic, "test_TryAssembleProgram_should_outputErrorNoMatchingOverload_when_instructionHasUndefinedMnemonic", 172);
  run_test(test_TryAssembleProgram_should_outputErrorUndefinedLabel_when_instructionReferencesUndefinedLabel, "test_TryAssembleProgram_should_outputErrorUndefinedLabel_when_instructionReferencesUndefinedLabel", 188);

  return UNITY_END();
}
