/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "assembler/assemble.h"
#include "processor/process.h"
#include "processor/instruction.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_tryAssemble_should_outputInstructionBytes_when_lineIsValidAssemblyInstruction(void);
extern void test_tryAssemble_should_outputDataBytes_when_lineIsValidAssemblyData(void);
extern void test_tryAssemble_should_outputInstructionWithReference_when_instructionReferencesInstruction(void);
extern void test_tryAssemble_should_outputInstructionWithReference_when_instructionReferencesData(void);
extern void test_tryAssemble_should_outputErrorTooFewParams_when_instructionHasTooFewParams(void);
extern void test_tryAssemble_should_outputErrorTooManyParams_when_instructionHasTooManyParams(void);
extern void test_tryAssemble_should_outputErrorExpectedRegister_when_instructionHasImmediateValueInsteadOfRegister(void);
extern void test_tryAssemble_should_outputErrorExpectedImmediateValue_when_instructionHasRegisterInsteadOfUnder16BitImmediateValue(void);
extern void test_tryAssemble_should_outputErrorExpectedImmediateValueOrLabelRef_when_instructionHasRegisterInsteadOf16BitImmediateValue(void);
extern void test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(enum Opcode opcode, bool needsRegister, signed int immediateValue);
extern void test_tryAssemble_should_outputErrorInvalidInstruction_when_instructionHasUndefinedOpcode(void);
extern void test_tryAssemble_should_outputErrorUndefinedLabel_when_instructionReferencesUndefinedLabel(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======Parameterized Test Wrappers=====*/
static void runner_args1_test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(void)
{
    test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(JMP, false, -1);
}
static void runner_args2_test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(void)
{
    test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(JMP, false, 0x10000);
}
static void runner_args3_test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(void)
{
    test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(LDIB, false, -1);
}
static void runner_args4_test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(void)
{
    test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(LDIB, false, 0x100);
}
static void runner_args5_test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(void)
{
    test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(INC, true, -1);
}
static void runner_args6_test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(void)
{
    test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(INC, true, 0x10);
}
static void runner_args7_test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(void)
{
    test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(LDMB, true, -9);
}
static void runner_args8_test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(void)
{
    test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(LDMB, true, 8);
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin(".\\assembler\\tests\\assemble_tests.c");
  run_test(test_tryAssemble_should_outputInstructionBytes_when_lineIsValidAssemblyInstruction, "test_tryAssemble_should_outputInstructionBytes_when_lineIsValidAssemblyInstruction", 18);
  run_test(test_tryAssemble_should_outputDataBytes_when_lineIsValidAssemblyData, "test_tryAssemble_should_outputDataBytes_when_lineIsValidAssemblyData", 49);
  run_test(test_tryAssemble_should_outputInstructionWithReference_when_instructionReferencesInstruction, "test_tryAssemble_should_outputInstructionWithReference_when_instructionReferencesInstruction", 72);
  run_test(test_tryAssemble_should_outputInstructionWithReference_when_instructionReferencesData, "test_tryAssemble_should_outputInstructionWithReference_when_instructionReferencesData", 111);
  run_test(test_tryAssemble_should_outputErrorTooFewParams_when_instructionHasTooFewParams, "test_tryAssemble_should_outputErrorTooFewParams_when_instructionHasTooFewParams", 149);
  run_test(test_tryAssemble_should_outputErrorTooManyParams_when_instructionHasTooManyParams, "test_tryAssemble_should_outputErrorTooManyParams_when_instructionHasTooManyParams", 174);
  run_test(test_tryAssemble_should_outputErrorExpectedRegister_when_instructionHasImmediateValueInsteadOfRegister, "test_tryAssemble_should_outputErrorExpectedRegister_when_instructionHasImmediateValueInsteadOfRegister", 201);
  run_test(test_tryAssemble_should_outputErrorExpectedImmediateValue_when_instructionHasRegisterInsteadOfUnder16BitImmediateValue, "test_tryAssemble_should_outputErrorExpectedImmediateValue_when_instructionHasRegisterInsteadOfUnder16BitImmediateValue", 227);
  run_test(test_tryAssemble_should_outputErrorExpectedImmediateValueOrLabelRef_when_instructionHasRegisterInsteadOf16BitImmediateValue, "test_tryAssemble_should_outputErrorExpectedImmediateValueOrLabelRef_when_instructionHasRegisterInsteadOf16BitImmediateValue", 253);
  run_test(runner_args1_test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange, "test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(JMP, false, -1)", 286);
  run_test(runner_args2_test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange, "test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(JMP, false, 0x10000)", 286);
  run_test(runner_args3_test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange, "test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(LDIB, false, -1)", 286);
  run_test(runner_args4_test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange, "test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(LDIB, false, 0x100)", 286);
  run_test(runner_args5_test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange, "test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(INC, true, -1)", 286);
  run_test(runner_args6_test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange, "test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(INC, true, 0x10)", 286);
  run_test(runner_args7_test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange, "test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(LDMB, true, -9)", 286);
  run_test(runner_args8_test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange, "test_tryAssemble_should_outputErrorImmediateValueOutOfRange_when_instructionHasImmediateValueOutOfRange(LDMB, true, 8)", 286);
  run_test(test_tryAssemble_should_outputErrorInvalidInstruction_when_instructionHasUndefinedOpcode, "test_tryAssemble_should_outputErrorInvalidInstruction_when_instructionHasUndefinedOpcode", 312);
  run_test(test_tryAssemble_should_outputErrorUndefinedLabel_when_instructionReferencesUndefinedLabel, "test_tryAssemble_should_outputErrorUndefinedLabel_when_instructionReferencesUndefinedLabel", 332);

  return UNITY_END();
}
