/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "test_utilities/text_assertions.h"
#include "parser/parse.h"
#include <string.h>
#include <stdbool.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_TryParseAssemblyLine_should_succeedWithInstructionLine_when_lineIsValidInstruction(void);
extern void test_TryParseAssemblyLine_should_succeedWithInstructionLine_when_lineIsValidInstructionWithComment(void);
extern void test_TryParseAssemblyLine_should_succeedWithDataLine_when_lineIsValidData(void);
extern void test_TryParseAssemblyLine_should_succeedWithDataLine_when_lineIsValidDataWithComment(void);
extern void test_TryParseAssemblyLine_should_succeedWithLabelLine_when_lineIsValidLabelWithName(void);
extern void test_TryParseAssemblyLine_should_succeedWithLabelLine_when_lineIsValidLabelWithNameAndComment(void);
extern void test_TryParseAssemblyLine_should_succeedWithLabelLine_when_lineIsValidLabelWithAddress(void);
extern void test_TryParseAssemblyLine_should_succeedWithLabelLine_when_lineIsValidLabelWithNameAndAddress(void);
extern void test_TryParseAssemblyLine_should_succeedAndAdvanceToEndOfFile_when_lastLine(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidLabelName_when_labelNameIsEmpty(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidLabelAddress_when_labelAddressIsEmpty(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidLabelAddress_when_labelAddressIsTooLarge(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidOpcode_when_firstWordIsNotValidOpcode(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidParameter_when_parameterIsNotRegisterOrHexValueOrReferenceOrInteger(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidParameter_when_lineEndsAfterComma(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidRegister_when_dollarSignFollowedByInvalidRegisterName(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidHexValue_when_zeroExFollowedByInvalidHexDigit(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidHexValue_when_hexParameterIsGreaterThanMaxUnsignedInteger(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidIntValue_when_integerParameterIsGreaterThanMaxSignedInteger(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidIntValue_when_integerParameterIsLessThanMinSignedInteger(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidByte_when_dataLineContainsInvalidByte(void);
extern void test_TryParseAssemblyLine_should_failWithUnexpectedCharacter_when_invalidCharacterAfterValidParameter(void);
extern void test_TryParseAssemblyLine_should_failWithUnexpectedCharacter_when_missingCommaBetweenParameters(void);
extern void test_TryParseAssemblyLine_should_failWithUnexpectedCharacter_when_invalidCharacterAfterLabel(void);
extern void test_TryParseAssemblyLine_should_failWithUnexpectedEndOfFile_when_onlyEmptyLine(void);
extern void test_TryParseAssemblyLine_should_failWithUnexpectedEndOfFile_when_atEndOfFile(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======Parameterized Test Wrappers=====*/

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("./parser/tests/parse_tests.c");
  run_test(test_TryParseAssemblyLine_should_succeedWithInstructionLine_when_lineIsValidInstruction, "test_TryParseAssemblyLine_should_succeedWithInstructionLine_when_lineIsValidInstruction", 26);
  run_test(test_TryParseAssemblyLine_should_succeedWithInstructionLine_when_lineIsValidInstructionWithComment, "test_TryParseAssemblyLine_should_succeedWithInstructionLine_when_lineIsValidInstructionWithComment", 63);
  run_test(test_TryParseAssemblyLine_should_succeedWithDataLine_when_lineIsValidData, "test_TryParseAssemblyLine_should_succeedWithDataLine_when_lineIsValidData", 85);
  run_test(test_TryParseAssemblyLine_should_succeedWithDataLine_when_lineIsValidDataWithComment, "test_TryParseAssemblyLine_should_succeedWithDataLine_when_lineIsValidDataWithComment", 105);
  run_test(test_TryParseAssemblyLine_should_succeedWithLabelLine_when_lineIsValidLabelWithName, "test_TryParseAssemblyLine_should_succeedWithLabelLine_when_lineIsValidLabelWithName", 125);
  run_test(test_TryParseAssemblyLine_should_succeedWithLabelLine_when_lineIsValidLabelWithNameAndComment, "test_TryParseAssemblyLine_should_succeedWithLabelLine_when_lineIsValidLabelWithNameAndComment", 146);
  run_test(test_TryParseAssemblyLine_should_succeedWithLabelLine_when_lineIsValidLabelWithAddress, "test_TryParseAssemblyLine_should_succeedWithLabelLine_when_lineIsValidLabelWithAddress", 167);
  run_test(test_TryParseAssemblyLine_should_succeedWithLabelLine_when_lineIsValidLabelWithNameAndAddress, "test_TryParseAssemblyLine_should_succeedWithLabelLine_when_lineIsValidLabelWithNameAndAddress", 189);
  run_test(test_TryParseAssemblyLine_should_succeedAndAdvanceToEndOfFile_when_lastLine, "test_TryParseAssemblyLine_should_succeedAndAdvanceToEndOfFile_when_lastLine", 211);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidLabelName_when_labelNameIsEmpty, "test_TryParseAssemblyLine_should_failWithInvalidLabelName_when_labelNameIsEmpty", 231);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidLabelAddress_when_labelAddressIsEmpty, "test_TryParseAssemblyLine_should_failWithInvalidLabelAddress_when_labelAddressIsEmpty", 248);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidLabelAddress_when_labelAddressIsTooLarge, "test_TryParseAssemblyLine_should_failWithInvalidLabelAddress_when_labelAddressIsTooLarge", 265);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidOpcode_when_firstWordIsNotValidOpcode, "test_TryParseAssemblyLine_should_failWithInvalidOpcode_when_firstWordIsNotValidOpcode", 282);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidParameter_when_parameterIsNotRegisterOrHexValueOrReferenceOrInteger, "test_TryParseAssemblyLine_should_failWithInvalidParameter_when_parameterIsNotRegisterOrHexValueOrReferenceOrInteger", 299);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidParameter_when_lineEndsAfterComma, "test_TryParseAssemblyLine_should_failWithInvalidParameter_when_lineEndsAfterComma", 316);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidRegister_when_dollarSignFollowedByInvalidRegisterName, "test_TryParseAssemblyLine_should_failWithInvalidRegister_when_dollarSignFollowedByInvalidRegisterName", 333);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidHexValue_when_zeroExFollowedByInvalidHexDigit, "test_TryParseAssemblyLine_should_failWithInvalidHexValue_when_zeroExFollowedByInvalidHexDigit", 350);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidHexValue_when_hexParameterIsGreaterThanMaxUnsignedInteger, "test_TryParseAssemblyLine_should_failWithInvalidHexValue_when_hexParameterIsGreaterThanMaxUnsignedInteger", 367);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidIntValue_when_integerParameterIsGreaterThanMaxSignedInteger, "test_TryParseAssemblyLine_should_failWithInvalidIntValue_when_integerParameterIsGreaterThanMaxSignedInteger", 384);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidIntValue_when_integerParameterIsLessThanMinSignedInteger, "test_TryParseAssemblyLine_should_failWithInvalidIntValue_when_integerParameterIsLessThanMinSignedInteger", 401);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidByte_when_dataLineContainsInvalidByte, "test_TryParseAssemblyLine_should_failWithInvalidByte_when_dataLineContainsInvalidByte", 418);
  run_test(test_TryParseAssemblyLine_should_failWithUnexpectedCharacter_when_invalidCharacterAfterValidParameter, "test_TryParseAssemblyLine_should_failWithUnexpectedCharacter_when_invalidCharacterAfterValidParameter", 435);
  run_test(test_TryParseAssemblyLine_should_failWithUnexpectedCharacter_when_missingCommaBetweenParameters, "test_TryParseAssemblyLine_should_failWithUnexpectedCharacter_when_missingCommaBetweenParameters", 452);
  run_test(test_TryParseAssemblyLine_should_failWithUnexpectedCharacter_when_invalidCharacterAfterLabel, "test_TryParseAssemblyLine_should_failWithUnexpectedCharacter_when_invalidCharacterAfterLabel", 469);
  run_test(test_TryParseAssemblyLine_should_failWithUnexpectedEndOfFile_when_onlyEmptyLine, "test_TryParseAssemblyLine_should_failWithUnexpectedEndOfFile_when_onlyEmptyLine", 486);
  run_test(test_TryParseAssemblyLine_should_failWithUnexpectedEndOfFile_when_atEndOfFile, "test_TryParseAssemblyLine_should_failWithUnexpectedEndOfFile_when_atEndOfFile", 503);

  return UNITY_END();
}
