/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "parser/parse.h"
#include <string.h>
#include <stdbool.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_TryParseAssemblyLine_should_succeedWithInstructionLine_when_lineIsValidInstruction(void);
extern void test_TryParseAssemblyLine_should_succeedWithDataLine_when_lineIsValidData(void);
extern void test_TryParseAssemblyLine_should_succeedWithLabel_when_textStartsWithLabel(void);
extern void test_TryParseAssemblyLine_should_succeedAndAdvanceToEndOfFile_when_lastLine(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidLabel_when_labelIsEmpty(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidLabel_when_noValidLabelCharacters(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidOpcode_when_firstWordIsNotValidOpcode(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidParameter_when_parameterIsNotRegisterOrHexValueOrReferenceOrInteger(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidParameter_when_lineEndsAfterComma(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidRegister_when_dollarSignFollowedByInvalidRegisterName(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidHexValue_when_zeroExFollowedByInvalidHexDigit(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidHexValue_when_hexParameterIsGreaterThanMaxUnsignedInteger(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidIntValue_when_integerParameterIsGreaterThanMaxSignedInteger(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidIntValue_when_integerParameterIsLessThanMinSignedInteger(void);
extern void test_TryParseAssemblyLine_should_failWithInvalidByte_when_dataLineContainsInvalidByte(void);
extern void test_TryParseAssemblyLine_should_failWithUnexpectedCharacter_when_invalidCharacterAfterValidParameter(void);
extern void test_TryParseAssemblyLine_should_failWithUnexpectedCharacter_when_missingCommaBetweenParameters(void);
extern void test_TryParseAssemblyLine_should_failWithUnexpectedCharacter_when_invalidCharacterAfterLabel(void);
extern void test_TryParseAssemblyLine_should_failWithUnexpectedEndOfFile_when_noMoreText(void);
extern void test_TryParseAssemblyLine_should_failWithUnexpectedEndOfFile_when_atEndOfFile(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======Parameterized Test Wrappers=====*/

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("./parser/tests/parse_tests.c");
  run_test(test_TryParseAssemblyLine_should_succeedWithInstructionLine_when_lineIsValidInstruction, "test_TryParseAssemblyLine_should_succeedWithInstructionLine_when_lineIsValidInstruction", 20);
  run_test(test_TryParseAssemblyLine_should_succeedWithDataLine_when_lineIsValidData, "test_TryParseAssemblyLine_should_succeedWithDataLine_when_lineIsValidData", 56);
  run_test(test_TryParseAssemblyLine_should_succeedWithLabel_when_textStartsWithLabel, "test_TryParseAssemblyLine_should_succeedWithLabel_when_textStartsWithLabel", 75);
  run_test(test_TryParseAssemblyLine_should_succeedAndAdvanceToEndOfFile_when_lastLine, "test_TryParseAssemblyLine_should_succeedAndAdvanceToEndOfFile_when_lastLine", 94);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidLabel_when_labelIsEmpty, "test_TryParseAssemblyLine_should_failWithInvalidLabel_when_labelIsEmpty", 113);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidLabel_when_noValidLabelCharacters, "test_TryParseAssemblyLine_should_failWithInvalidLabel_when_noValidLabelCharacters", 129);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidOpcode_when_firstWordIsNotValidOpcode, "test_TryParseAssemblyLine_should_failWithInvalidOpcode_when_firstWordIsNotValidOpcode", 145);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidParameter_when_parameterIsNotRegisterOrHexValueOrReferenceOrInteger, "test_TryParseAssemblyLine_should_failWithInvalidParameter_when_parameterIsNotRegisterOrHexValueOrReferenceOrInteger", 161);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidParameter_when_lineEndsAfterComma, "test_TryParseAssemblyLine_should_failWithInvalidParameter_when_lineEndsAfterComma", 177);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidRegister_when_dollarSignFollowedByInvalidRegisterName, "test_TryParseAssemblyLine_should_failWithInvalidRegister_when_dollarSignFollowedByInvalidRegisterName", 193);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidHexValue_when_zeroExFollowedByInvalidHexDigit, "test_TryParseAssemblyLine_should_failWithInvalidHexValue_when_zeroExFollowedByInvalidHexDigit", 209);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidHexValue_when_hexParameterIsGreaterThanMaxUnsignedInteger, "test_TryParseAssemblyLine_should_failWithInvalidHexValue_when_hexParameterIsGreaterThanMaxUnsignedInteger", 225);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidIntValue_when_integerParameterIsGreaterThanMaxSignedInteger, "test_TryParseAssemblyLine_should_failWithInvalidIntValue_when_integerParameterIsGreaterThanMaxSignedInteger", 241);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidIntValue_when_integerParameterIsLessThanMinSignedInteger, "test_TryParseAssemblyLine_should_failWithInvalidIntValue_when_integerParameterIsLessThanMinSignedInteger", 257);
  run_test(test_TryParseAssemblyLine_should_failWithInvalidByte_when_dataLineContainsInvalidByte, "test_TryParseAssemblyLine_should_failWithInvalidByte_when_dataLineContainsInvalidByte", 273);
  run_test(test_TryParseAssemblyLine_should_failWithUnexpectedCharacter_when_invalidCharacterAfterValidParameter, "test_TryParseAssemblyLine_should_failWithUnexpectedCharacter_when_invalidCharacterAfterValidParameter", 289);
  run_test(test_TryParseAssemblyLine_should_failWithUnexpectedCharacter_when_missingCommaBetweenParameters, "test_TryParseAssemblyLine_should_failWithUnexpectedCharacter_when_missingCommaBetweenParameters", 305);
  run_test(test_TryParseAssemblyLine_should_failWithUnexpectedCharacter_when_invalidCharacterAfterLabel, "test_TryParseAssemblyLine_should_failWithUnexpectedCharacter_when_invalidCharacterAfterLabel", 321);
  run_test(test_TryParseAssemblyLine_should_failWithUnexpectedEndOfFile_when_noMoreText, "test_TryParseAssemblyLine_should_failWithUnexpectedEndOfFile_when_noMoreText", 337);
  run_test(test_TryParseAssemblyLine_should_failWithUnexpectedEndOfFile_when_atEndOfFile, "test_TryParseAssemblyLine_should_failWithUnexpectedEndOfFile_when_atEndOfFile", 353);

  return UNITY_END();
}
