// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "'UQQOPOOOiOPO'#CaO}OPO'#C_O!SOPO'#C`O!bOPO'#CcO!pOPO'#C^O#ROPO'#C^OOOO'#C^'#C^O#^OPO'#C^Q#rOPOOO#wOPO,58yO$]OPO,58yO$bOQO,58zO$vOSO,58}O%UOPO,58}OOOO'#Ca'#CaOOOO,58x,58xO%dOPO,58xO%oOPO,58xOQOPO'#CgQ#rOPOOOOOO1G.e1G.eO&QOPO1G.eOOOO'#Cb'#CbO&fOPO1G.fOOOO,59Q,59QO&wOSO1G.iOOOO-E6d-E6dOOOO1G.d1G.dO'VOPO1G.dOOOO,59R,59ROOOO-E6e-E6eOOOO7+$P7+$PO'bOQO'#CeO'pOPO7+$QO(OOPO7+$QP(aOSO'#CfOOOO7+$O7+$OOOOO,59P,59PO'eOQO,59PO(fOQO,59PO(tOPO<<GlOOOO-E6c-E6cOOOO1G.k1G.kO'eOQO1G.kP)SOPO'#CeOOOO7+$V7+$V",
  stateData: ")X~OWVO]WO^PO_QOeSO[QPgQP~O_ZO`YOWTX[TX]TXgTX~O`YO~O][OWSX[SXgSX~O]]OWVX[VXgVX~OW`O^_OeSO[QXgQX~OW`O[QXgQX~OW`O^PO_QOeSO[QXgQX~OgcO~O]eOWRa[Ra^RaeRagRa~O`fO~OagObgOcgOWSa[SagSa~OfiOWVa[VagVa~O]jOWVa[VagVa~OWlO[QagQa~OWlO^_OeSO[QagQa~O]pOWRi[Ri^RieRigRi~O]rOdqOWSi[SigSi~OfiOWVi[VigVi~OWuO[QigQi~O]wOagObgOcgO~OdxOWSq[SqgSq~O]yOdqOWSq[SqgSq~OfiO~O]|OagObgOcgO~OdxOWSy[SygSy~OdxO~O",
  goto: "!m[PP]cju|jP!Z!a!gQXORncSTOcRbWSUOcSaTWRmbZROTWbcQh[QvqS{wxR!O|QshRzsQ^SRk^QdXRod",
  nodeNames: "⚠ Program Line Label Instruction Mnemonic Operand Data Comment",
  maxTerm: 23,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: ",Y~RbXY!ZYZ!fpq!Ztu!k{|#]|}#k}!O#]!O!P#p!Q!R$_!R!['p![!](Z!]!^(`!b!c(w!c!i+q!i!}%x#R#S%x#T#Z+q#Z#o%x~!`Q]~XY!Zpq!Z~!kOg~~!nS!Q![!z!c!}!z#R#S!z#T#o!z~#PSa~!Q![!z!c!}!z#R#S!z#T#o!zQ#`P!Q![#cQ#hPbQ!Q![#c~#pOd~~#sP#W#X#v~#yP#T#U#|~$PP#h#i$S~$VP#T#U$Y~$_Oe~V$fWbQ^P!Q![%O!c!i&Z!i!}%x#R#S%x#T#Z&Z#Z#l%x#l#m&n#m#o%xV%XSfSbQ^P!Q![%e!c!}%x#R#S%x#T#o%xR%lSbQ^P!Q![%e!c!}%x#R#S%x#T#o%xP%}S^P!Q![%x!c!}%x#R#S%x#T#o%xT&bSfS^P!Q![%x!c!}%x#R#S%x#T#o%xR&sU^P!Q!['V!c!i'V!i!}%x#R#S%x#T#Z'V#Z#o%xR'^UbQ^P!Q!['V!c!i'V!i!}%x#R#S%x#T#Z'V#Z#o%xV'wUbQ^P!Q![%O!c!i&Z!i!}%x#R#S%x#T#Z&Z#Z#o%x~(`O`~~(eSW~OY(`Z;'S(`;'S;=`(q<%lO(`~(tP;=`<%l(`R(zU!Q![)^!c!i)^!i!}+`#R#S+`#T#Z)^#Z#o+`R)eU_PcQ!Q![)w!c!i)w!i!}+`#R#S+`#T#Z)w#Z#o+`R*OU_PcQ!Q![*b!c!i*b!i!}+`#R#S+`#T#Z*b#Z#o+`R*iU_PcQ!Q![*{!c!i*{!i!}+`#R#S+`#T#Z*{#Z#o+`R+SS_PcQ!Q![+`!c!}+`#R#S+`#T#o+`Q+eScQ!Q![+`!c!}+`#R#S+`#T#o+`T+vU^P!Q![&Z!c!i&Z!i!}%x#R#S%x#T#Z&Z#Z#o%x",
  tokenizers: [0, 1, 2],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
