/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "custom_assertions.h"
#include "processor/instruction.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_fetchInstruction_shouldLoadOpcode_whenOpcodeHasLayoutNone(void);
extern void test_fetchInstruction_shouldLoad8BitImmediateValue_whenOpcodeHasLayoutImm8(void);
extern void test_fetchInstruction_shouldLoadRegisterAAnd4BitImmediateValue_whenOpcodeHasLayoutRegAImm4(void);
extern void test_fetchInstruction_shouldLoadRegisterAAndRegisterB_whenOpcodeHasLayoutRegARegB(void);
extern void test_fetchInstruction_shouldLoad16BitImmediateValue_whenOpcodeHasLayoutImm16(void);
extern void test_storeInstruction_shouldSaveOpcode_whenOpcodeHasLayoutNone(void);
extern void test_storeInstruction_shouldSave8BitImmediateValue_whenOpcodeHasLayoutImm8(void);
extern void test_storeInstruction_shouldSaveRegisterAAnd4BitImmediateValue_whenOpcodeHasLayoutRegAImm4(void);
extern void test_storeInstruction_shouldSaveRegisterAAndRegisterB_whenOpcodeHasLayoutRegARegB(void);
extern void test_storeInstruction_shouldSave16BitImmediateValue_whenOpcodeHasLayoutImm16(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======Parameterized Test Wrappers=====*/

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("./processor/tests/instruction_tests.c");
  run_test(test_fetchInstruction_shouldLoadOpcode_whenOpcodeHasLayoutNone, "test_fetchInstruction_shouldLoadOpcode_whenOpcodeHasLayoutNone", 18);
  run_test(test_fetchInstruction_shouldLoad8BitImmediateValue_whenOpcodeHasLayoutImm8, "test_fetchInstruction_shouldLoad8BitImmediateValue_whenOpcodeHasLayoutImm8", 33);
  run_test(test_fetchInstruction_shouldLoadRegisterAAnd4BitImmediateValue_whenOpcodeHasLayoutRegAImm4, "test_fetchInstruction_shouldLoadRegisterAAnd4BitImmediateValue_whenOpcodeHasLayoutRegAImm4", 49);
  run_test(test_fetchInstruction_shouldLoadRegisterAAndRegisterB_whenOpcodeHasLayoutRegARegB, "test_fetchInstruction_shouldLoadRegisterAAndRegisterB_whenOpcodeHasLayoutRegARegB", 65);
  run_test(test_fetchInstruction_shouldLoad16BitImmediateValue_whenOpcodeHasLayoutImm16, "test_fetchInstruction_shouldLoad16BitImmediateValue_whenOpcodeHasLayoutImm16", 81);
  run_test(test_storeInstruction_shouldSaveOpcode_whenOpcodeHasLayoutNone, "test_storeInstruction_shouldSaveOpcode_whenOpcodeHasLayoutNone", 113);
  run_test(test_storeInstruction_shouldSave8BitImmediateValue_whenOpcodeHasLayoutImm8, "test_storeInstruction_shouldSave8BitImmediateValue_whenOpcodeHasLayoutImm8", 127);
  run_test(test_storeInstruction_shouldSaveRegisterAAnd4BitImmediateValue_whenOpcodeHasLayoutRegAImm4, "test_storeInstruction_shouldSaveRegisterAAnd4BitImmediateValue_whenOpcodeHasLayoutRegAImm4", 142);
  run_test(test_storeInstruction_shouldSaveRegisterAAndRegisterB_whenOpcodeHasLayoutRegARegB, "test_storeInstruction_shouldSaveRegisterAAndRegisterB_whenOpcodeHasLayoutRegARegB", 157);
  run_test(test_storeInstruction_shouldSave16BitImmediateValue_whenOpcodeHasLayoutImm16, "test_storeInstruction_shouldSave16BitImmediateValue_whenOpcodeHasLayoutImm16", 172);

  return UNITY_END();
}
