// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Line = 2,
  Label = 3,
  Instruction = 4,
  Mnemonic = 5,
  Operand = 6,
  Data = 7,
  Comment = 8
