#pragma once
#include "processor/operand.h"

// A code indicating which action the processor should perform for a given instruction.
// Representable by one byte.
typedef enum ProcessorOpcode {
  PROCESSOR_OPCODE_NOP,

  PROCESSOR_OPCODE_JMP_R,
  PROCESSOR_OPCODE_JMP_I,
  
  PROCESSOR_OPCODE_JMZ_R,
  PROCESSOR_OPCODE_JMZ_I,
  
  PROCESSOR_OPCODE_SLP_R,
  PROCESSOR_OPCODE_SLP_I,
  
  PROCESSOR_OPCODE_SET_R,
  PROCESSOR_OPCODE_SET_I,
  
  PROCESSOR_OPCODE_LDB_R,
  PROCESSOR_OPCODE_LDB_I,
  
  PROCESSOR_OPCODE_LDW_R,
  PROCESSOR_OPCODE_LDW_I,
  
  PROCESSOR_OPCODE_STB_RR,
  PROCESSOR_OPCODE_STB_RI,
  PROCESSOR_OPCODE_STB_IR,
  PROCESSOR_OPCODE_STB_II,
  
  PROCESSOR_OPCODE_STW_RR,
  PROCESSOR_OPCODE_STW_RI,
  PROCESSOR_OPCODE_STW_IR,
  PROCESSOR_OPCODE_STW_II,
  
  PROCESSOR_OPCODE_PSHB,
  
  PROCESSOR_OPCODE_PSHW,
  
  PROCESSOR_OPCODE_POPB,
  
  PROCESSOR_OPCODE_POPW,
  
  PROCESSOR_OPCODE_ADD_R,
  PROCESSOR_OPCODE_ADD_I,
  
  PROCESSOR_OPCODE_SUB_RR,
  PROCESSOR_OPCODE_SUB_RI,
  PROCESSOR_OPCODE_SUB_IR,
  
  PROCESSOR_OPCODE_MUL_R,
  PROCESSOR_OPCODE_MUL_I,
  
  PROCESSOR_OPCODE_DIVS_RR,
  PROCESSOR_OPCODE_DIVS_RI,
  PROCESSOR_OPCODE_DIVS_IR,
  
  PROCESSOR_OPCODE_DIVU_RR,
  PROCESSOR_OPCODE_DIVU_RI,
  PROCESSOR_OPCODE_DIVU_IR,
  
  PROCESSOR_OPCODE_REMS_RR,
  PROCESSOR_OPCODE_REMS_RI,
  PROCESSOR_OPCODE_REMS_IR,
  
  PROCESSOR_OPCODE_REMU_RR,
  PROCESSOR_OPCODE_REMU_RI,
  PROCESSOR_OPCODE_REMU_IR,
  
  PROCESSOR_OPCODE_AND_R,
  PROCESSOR_OPCODE_AND_I,
  
  PROCESSOR_OPCODE_IOR_R,
  PROCESSOR_OPCODE_IOR_I,
  
  PROCESSOR_OPCODE_XOR_R,
  PROCESSOR_OPCODE_XOR_I,
  
  PROCESSOR_OPCODE_LSH_RR,
  PROCESSOR_OPCODE_LSH_RI,
  PROCESSOR_OPCODE_LSH_IR,
  
  PROCESSOR_OPCODE_RSHS_RR,
  PROCESSOR_OPCODE_RSHS_RI,
  PROCESSOR_OPCODE_RSHS_IR,
  
  PROCESSOR_OPCODE_RSHU_RR,
  PROCESSOR_OPCODE_RSHU_RI,
  PROCESSOR_OPCODE_RSHU_IR,
  
  PROCESSOR_OPCODE_CEQ_R,
  PROCESSOR_OPCODE_CEQ_I,
  
  PROCESSOR_OPCODE_CNE_R,
  PROCESSOR_OPCODE_CNE_I,
  
  PROCESSOR_OPCODE_CLTS_RR,
  PROCESSOR_OPCODE_CLTS_RI,
  PROCESSOR_OPCODE_CLTS_IR,
  
  PROCESSOR_OPCODE_CLTU_RR,
  PROCESSOR_OPCODE_CLTU_RI,
  PROCESSOR_OPCODE_CLTU_IR,
  
  PROCESSOR_OPCODE_CGES_RR,
  PROCESSOR_OPCODE_CGES_RI,
  PROCESSOR_OPCODE_CGES_IR,
  
  PROCESSOR_OPCODE_CGEU_RR,
  PROCESSOR_OPCODE_CGEU_RI,
  PROCESSOR_OPCODE_CGEU_IR,

  PROCESSOR_OPCODE_COUNT
} ProcessorOpcode;

// Describes the details of a particular opcode.
struct OpcodeInfo {
  const char* name;
  struct ParameterLayout parameterLayout;
  // TODO: Consider adding function pointer for implementation.
};

// The details of each opcode. Can be indexed directly by a valid Opcode value.
extern const struct OpcodeInfo OPCODE_INFO[];

// Converts a byte to an opcode.
// Returns NOP if the byte is not a valid opcode.
// Note: A valid opcode can safely be cast to an unsigned char to obtain its byte value.
enum Opcode byteToOpcode(unsigned char byte);
