if(CMAKE_COMPILER_IS_GNUCC)
  add_compile_options(-Wall -Wextra)
elseif(CMAKE_COMPILER_IS_MSVC)
  add_compile_options(/W4)
elseif(CMAKE_COMPILER_IS_CLANG)
  add_compile_options(-Wall -Wextra)
endif()

set(CMAKE_COMPILE_WARNING_AS_ERROR ON)
set(CMAKE_LINK_WARNING_AS_ERROR ON)
